//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirbnbUdc.Repository.Implementation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long Id { get; set; }
        public Nullable<int> RateForOwner { get; set; }
        public string CommentsForOwner { get; set; }
        public Nullable<int> RateForCustomer { get; set; }
        public string CommentsForCustomer { get; set; }
        public long ReservationId { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
