//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirbnbUdc.Repository.Implementation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultimediaType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MultimediaType()
        {
            this.PropertyMultimedia = new HashSet<PropertyMultimedia>();
        }
    
        public int Id { get; set; }
        public string MultimediaTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyMultimedia> PropertyMultimedia { get; set; }
    }
}
