//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirbnbUdc.Repository.Implementation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyMultimedia
    {
        public long Id { get; set; }
        public Nullable<int> MultimediaName { get; set; }
        public string MultimediaLink { get; set; }
        public long PropertyId { get; set; }
        public int MultimediaTypeId { get; set; }
    
        public virtual MultimediaType MultimediaType { get; set; }
        public virtual Property Property { get; set; }
    }
}
